title: Juanita # your name (or website title) here
logo: "/images/datapresentation - mod.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Analyst <br><br>
  ğŸ“Š Data Analytics | Data Engineering | Business Intelligence | Analytics Engineering <br><br>
  ğŸ’» SQL | Python | Tableau | R <br><br>
  ğŸ“š Data Storytelling | Cloud Learning <br><br>
  ğŸ• Data Informed Dog Mom <br><br>
  <a href="https://www.linkedin.com/in/juanita-jj-palomar/"> LinkedIn Profile</a>
  <br><br>

  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
