title: Juanita # your name (or website title) here
logo: "/images/datapresentation - mod.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Analyst 
  â–¬â–¬â–¬â–¬â–¬â–¬â–¬â–¬â–¬â–¬â–¬â–¬â–¬â–¬â–¬ <br><br>
  ğŸ“Š Data Analytics | Data Engineering | <br>
  ğŸ’» Analytics Engineering | BI Analyst <br><br>
  âœ… SQL | Python | Tableau | Excel | R <br><br>
  ğŸ“¡ Communicating findings and key metrics to inform others <br><br>
  ğŸ“š Data Storytelling ğŸŒ¿ Climate Learning <br><br>
  ğŸ• Analytics Informed Dog Mom <br><br>
  â•”â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•— <br><br>

  <a href="https://www.linkedin.com/in/juanita-jj-palomar/"> LinkedIn Profile</a>
<br><br>

  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
