title: Juanita # your name (or website title) here
logo: "/images/datapresentation - mod.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Analyst 
  â–¬â–¬â–¬â–¬â–¬â–¬â–¬â–¬â–¬â–¬â–¬â–¬â–¬â–¬â–¬â–¬â–¬â–¬â–¬â–¬â–¬â–¬â–¬â–¬â–¬â–¬â–¬â–¬â–¬â–¬â–¬â–¬ <br><br>
 ğŸ•µï¸â€â™€ï¸ Analytics Engineering | <br>
 ğŸ‘©â€ğŸ« Business Analyst <br>br> | ğŸ’» Business Intelligence <br><br>
 ğŸ‘©â€ğŸ’» Data Engineering | <br><br>
 ğŸ“Š Translating metrics to inform others | <br><br>
 âœ… SQL | Python | Tableau | Excel | R <br><br>
 ğŸ“š Data Storytelling | Always Learning <br><br>
 ğŸ• Analytics Informed Dog Mom <br><br>
  â•”â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•—<br><br>  
  <a href="https://www.linkedin.com/in/juanita-jj-palomar/"> LinkedIn Profile</a>

  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
