title: Juanita # your name (or website title) here
logo: "/images/datapresentation - mod.jpg?raw=true" # your photo (or logo) here
description: >  # your text below (remove <br> elements if you don't need line breaks)

  â–¬â–¬â–¬â–¬â–¬â–¬â–¬â–¬â–¬â–¬â–¬â–¬â–¬â–¬â–¬ <br><br>
  Analytics Engineering | D/B Analytics <br>
  Data Engineering | Business Intelligence  <br>
  SQL | Python | Tableau | Excel | R <br><br>
  ğŸ“¡ Communicating findings and key metrics to inform others <br><br>
  ğŸ“š Data Storytelling ğŸŒ¿ Climate Learning <br>
  ğŸ• Analytics Informed Dog Mom <br><br>
  â•”â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•— <br><br>
  


 
 
theme: jekyll-theme-minimal

#google_analytics: UA-000000-0 # your Google Analytics tracking ID here
